# Generated by Django 5.0.1 on 2024-03-14 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('email', models.CharField(blank=True, max_length=20, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=350, verbose_name='name')),
                ('front', models.ImageField(upload_to='template/', verbose_name='front')),
                ('back', models.ImageField(upload_to='template/', verbose_name='back')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('phone_1', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('phone_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone')),
                ('phone_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone')),
                ('email_1', models.CharField(blank=True, max_length=50, verbose_name='email')),
                ('email_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('domicile', models.CharField(blank=True, max_length=50, null=True, verbose_name='Domicile')),
                ('organisation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organisation')),
                ('web_site', models.CharField(blank=True, max_length=50, null=True, verbose_name='Web site')),
                ('servise', models.CharField(blank=True, max_length=50, null=True, verbose_name='Servise')),
                ('function', models.CharField(blank=True, max_length=50, null=True, verbose_name='Function')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact/', verbose_name='image')),
                ('is_print', models.BooleanField(default=False)),
                ('print_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_dealer', to='card.dealer', verbose_name='Dealer')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_template', to='card.template', verbose_name='Template')),
            ],
        ),
    ]
