# Generated by Django 5.0.1 on 2024-03-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=50, verbose_name='key')),
                ('value', models.CharField(blank=True, max_length=50, verbose_name='value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_1',
            field=models.CharField(blank=True, max_length=50, verbose_name='email 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='email 2'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_1',
            field=models.CharField(blank=True, max_length=50, verbose_name='phone 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='phone 1'),
        ),
    ]
