# Generated by Django 5.0.1 on 2024-03-14 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_socialmedia_alter_contact_email_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_social', to='card.contact', verbose_name='Contact'),
        ),
    ]
