# Generated by Django 5.0.1 on 2024-03-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_socialmedia_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='print_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
