# Generated by Django 5.0.1 on 2024-03-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_contact_print_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='qr_information',
            field=models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='qr code info'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='domicile',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Domicile'),
        ),
    ]
