# Generated by Django 5.0.1 on 2024-04-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_contact_qr_information_alter_contact_domicile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='domicile',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Domicile'),
        ),
    ]
