# Generated by Django 5.0.1 on 2024-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_contact_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='organisation',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='servise',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Servise'),
        ),
    ]
