# Generated by Django 5.0.1 on 2024-03-02 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateurs'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
