# Generated by Django 5.0.1 on 2024-03-02 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=350, verbose_name='nom')),
                ('front', models.ImageField(upload_to='projet/', verbose_name='front')),
                ('back', models.ImageField(upload_to='projet/', verbose_name='back')),
            ],
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=350, null=True, verbose_name='matricule')),
                ('noms', models.CharField(blank=True, max_length=350, verbose_name='noms')),
                ('date_de_naissance', models.CharField(blank=True, max_length=350, verbose_name='Date de naissance')),
                ('promotion', models.CharField(blank=True, max_length=350, verbose_name='promotion')),
                ('image', models.ImageField(blank=True, default='student_image/student_avatar.png', upload_to='student_images/', verbose_name='image etudiant')),
                ('imprime', models.BooleanField(default=False, verbose_name='Imprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projet', to='cartes.projet')),
            ],
        ),
    ]
