# Generated by Django 5.0.1 on 2024-03-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='adresse',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='adresse'),
        ),
    ]
