# Generated by Django 5.0.1 on 2024-03-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0003_alter_carte_date_de_naissance_alter_carte_matricule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
