# Generated by Django 5.0.1 on 2024-03-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0004_carte_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carte',
            name='image_url',
        ),
    ]
